[workspace]
members = ["jack-voice", "jack-voice-bridge", "jack-voice-ws"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[patch.crates-io]
pocket-tts = { path = "../pocket-tts/crates/pocket-tts" }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
